### ISSUE TITLE
script/jsvar and classes

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#110]
I am not sure whether script/jsvar supporting classes or not. There is no error thrown but the behavior is not as expected.

```
import std.stdio;
import arsd.script, arsd.jsvar;

class Newsletter
{
	string subject;
}

void main()
{
	auto newsletter = new Newsletter();
	newsletter.subject = "ABC";
	
	var globals = var.emptyObject;
	globals.newsletter = newsletter;
	writeln(globals.newsletter.subject);
	
	string scriptSource = q{
		newsletter.subject = "123";
	};

	interpret(scriptSource, globals);
	writeln(newsletter.subject);
	writeln(globals.newsletter.subject);
}
```

Output:
null
ABC
123

**Comment by adamdruppe** [comment]
On Mon, Aug 21, 2017 at 08:29:54PM +0000, andre2007 wrote:
> I am not sure whether script/jsvar supporting classes or not. There is no error thrown but the behavior is not as expected.

The class support is weird right now, since I haven't found a way
that works reliably.

Right now, it copies the members into a script object rather than
referencing the original class.

You can wrap a class in a ref using...

http://dpldocs.info/experimental-docs/arsd.jsvar.wrapNativeObject.1.html

that wrapNativeObject function, but I don't think it wraps all the member
variables, just methods marked with @scriptable.

**Comment by andre2007** [comment]
Just by adding the UDA to the member attribute the code is working as expected. Thanks!

Some syntax sugar: Would it be possible to allow the UDA for the class itself to make all public members/method accessible in jsvar?

```
@scriptable class Newsletter
{
	string subject;
	
	void test2()
	{
		subject ~= "123";
	}
}
```

**Comment by adamdruppe** [comment]
On Tue, Aug 22, 2017 at 05:11:42PM +0000, andre2007 wrote:
> Some syntax sugar: Would it be possible to allow the UDA for the class itself to make all public members/method accessible in jsvar?

Maybe, perhaps it can check derivedMembers... I tried
something similar earlier and it failed cuz the inherited
members caused compile errors.

But you can do:

@scriptable:

at the top of the class, inside it to apply to everything.

**Comment by andre2007** [comment]
I forget about the colon option. This is as good as setting the class @scriptable. 
I close this ticket. Thanks a lot!
