### ISSUE TITLE
Some issues with terminal.d

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#115]
I have some issues to understand how to work with terminal.d under windows 10.

Issue 1: I want to define to define a Terminal variable in module scope so I can use it in different functions / methods. This will not compile:

```
import arsd.terminal;

Terminal terminal = null;

void main()
{
	terminal = Terminal(ConsoleOutputType.linear);
} 
```
How can I define a static terminal variable in module scope?

Issue 2: Due to issue 1 I have a local Terminal variable in different functions. But the output order in the console is wrong. This will output " World" "Hello":
```
import arsd.terminal;

void main()
{
	Terminal terminal = Terminal(ConsoleOutputType.linear);
	terminal.writeln("Hello");
	test();
}

void test()
{
	Terminal terminal = Terminal(ConsoleOutputType.linear);
	terminal.writeln(" World");
} 
```

Issue 3: By setting the font color to white, the text is outputted in the same color as Color.DEFAULT. 
Other colors working fine, but Color.white is same kind of gray which is the same color as the default console color.

**Comment by adamdruppe** [comment]
On Fri, Oct 13, 2017 at 05:21:58PM +0000, andre2007 wrote:
> Issue 1: I want to define to define a Terminal variable in module scope so I can use it in different functions / methods. This will not compile:

You can use a pointer instead:

Terminal* terminal;
void main() {
   Terminal terminalInstance = Terminal(ConsoleOutputType.linear);
   .terminal = &terminalInstance;
   scope(exit) .terminal = null;
}

> Issue 2: Due to issue 1 I have a local Terminal variable in different functions. But the output order in the console is wrong. This will output " World" "Hello":

When Terminal is destroyed, it flushes its buffer. So here the "hello" got buffered separately from "world" and it got flushed last.

You can use terminal.flush() to force it to flush faster.

> Issue 3: By setting the font color to white, the text is outputted in the same color as Color.DEFAULT. 

That's because the default on Windows is white (well, gray). The names
are approximations into a user-defined 8 color palette.

**Comment by andre2007** [comment]
Thanks a lot for your help Adam. The issues are solved for me. I also just found out, I can pass a number to the color method. This code will show a nice white font on black background color.

```
terminal.color(15, Color.black);
```

**Comment by adamdruppe** [comment]
On Fri, Oct 13, 2017 at 07:52:11PM +0000, andre2007 wrote:
> terminal.color(15, Color.black);

That's `Color.white | Bright`

...oh I might have forgot to actually document that. The Bright
modifier can brighten any of the colors (except DEFAULT).
