### ISSUE TITLE
Wrong result of getX11PropertyData on X64

### ISSUE THREAD

**Issue by zero-vector** [adamdruppe/arsd#117]
https://github.com/adamdruppe/arsd/blob/b4cf5d0c469538a8415f89bc8a920dd599e3dea6/simpledisplay.d#L3676

For the lack of understanding I don't create a PR, but  this seems to work:
```
version( X86_64 ) {
    auto byteLength = actualItems * actualFormat / 4;
}
else {
     auto byteLength = actualItems * actualFormat / 8;
}
```

**Comment by adamdruppe** [comment]
On Sat, Oct 14, 2017 at 04:16:57PM -0700, zero-vector wrote:
> For the lack of understanding I don't create a PR, but  this seems to work:

huh yeah, looks like you are right. from the man page:

If the returned format is 32, the returned data is represented
       as a long array and should be cast to that type to obtain the elements.

Well, you aren't exactly right... need to check for actualFormat == 32,
since /8 is correct everywhere else. what a pain i hate C.
