### ISSUE TITLE
cgi.d and post

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#127]
For the project https://github.com/metrue/fx I want to add support for the D Programming language. As http server library I would like to use cgi.d but I have some issues:

- If content-type "application/json" is used, there is an exception thrown here
https://github.com/adamdruppe/arsd/blob/master/cgi.d#L953

- I deactivated the exception and my next issue is, how I can get the post body?
cgi.post is a associative array with the post body as key and an empty value:
["{\n\t\"a\":3,\n\t\"b\":5\n\t\n}":""]
Is there a better way to retrieve the post body instead of reading the first key of the associative array?

- Should I include the file LICENSE next to the cgi.d I if create a pull request for the metrue/fx project?

**Comment by adamdruppe** [comment]
On Wed, Dec 13, 2017 at 12:12:09PM -0800, andre2007 wrote:
> - I deactivated the exception and my next issue is, how I can get the post body?

You can compile with -version=preserveData and then there's a member
cgi.originalPostData you can pull out of.

> cgi.post is a associative array with the post body as key and an empty value:
> ["{\n\t\"a\":3,\n\t\"b\":5\n\t\n}":""]

What we should do though is not throw the exception, but not run the
original processor either - actually add proper json support (well, at
least semi-proper json support, where it gives you the submitted string.
We might parse it too but cgi.d currently has no dependencies so it would
even be a std.json thing (blargh... but usable) or on a version flag.
I'd probably give it a new name like postedJson and maybe another flag
to check that tells what format we received.

This is fairly simple, but I won't be able to get to it myself until
at least tomorrow. (I never did it until now simply because I never
did json posts. Heck, even now, I still very rarely do.)

> - Should I include the file LICENSE next to the cgi.d I if create a pull request for the metrue/fx project?

doesn't matter to me.

**Comment by andre2007** [comment]
Thanks for the info and your help. The semi-proper json support is sufficient for my use case.

**Comment by andre2007** [comment]
There seems to be an issue with cgi.originalPostData. While cgi.post.keys[0] contains my Json string, cgi.originalPostData contains the string "[]"

**Comment by adamdruppe** [comment]
I'll be able to look at this soon, just finishing up work for the week now,
then I should have an hour.

**Comment by adamdruppe** [comment]
On Fri, Dec 15, 2017 at 11:25:42AM -0800, andre2007 wrote:
> There seems to be an issue with cgi.originalPostData. While cgi.post.keys[0] contains my Json string, cgi.originalPostData contains the string "[]"

are you using the -version=embedded_httpd ?

i see now that originalPostData is only preserved on the cgi modes.
easy change though.

**Comment by andre2007** [comment]
Yes I am using embedded_httpd. Thanks for having a look

**Comment by adamdruppe** [comment]
hey can you try the newest cgi.d now?

added a member called postJson that should work if the content
type is set. no special flags needed. hopefully.

**Comment by andre2007** [comment]
It is working great. Thanks a lot!
