### ISSUE TITLE
issue with images

### ISSUE THREAD

**Issue by ASHIT-AXAR** [adamdruppe/arsd#131]
hello adam.
i cannot create different instances of a image. 
```d
typeof(img).stringof
```
returns `MemoryImage`  that is interface and has no data that i can copy.

look at below code:

```d
import arsd.minigui;
import arsd.png;

void main(){
	auto window = new MainWindow("Hello");

	// layout to hold buttons
	auto hlButton = new HorizontalLayout(window);
	// buttons
	auto btnFilter = new Button("Filter", hlButton);
	auto btnCancel = new Button("Cancel", hlButton);
	// layout to hold ImageBoxes
	auto hlImage = new HorizontalLayout(window);
	// ImageBoxes
	auto img = readPng("ashit.png");
	auto img1 = new ImageBox(img, ImageBox.HowToFit.center, Color.transparent, hlImage);
	auto img2 = new ImageBox(img, ImageBox.HowToFit.center, Color.transparent, hlImage);
	// btnCancel event handler
	btnCancel.addEventListener("triggered", (Event e){ window.close;});
	// btnFilter event handler
	btnFilter.addEventListener("triggered", (Event e){
		auto m = img; // does not create a new instance !
		Color c;
		for (int y = 0; y < m.height; y++){
			for (int x = 0; x < m.width; x++){
				c = m.getPixel(x, y);
				c.g = 0;
				m.setPixel(x, y, c);
			}
		}
		img2.setImage(m);
	});
	
	window.loop;
}
```

i added below code to ImageBox source code in minigui to be able to set image again.

```d
	public void setImage(MemoryImage image){
		this.image_ = image;
		updateSprite();
		redraw();
	}
```

it looks working
![image](https://user-images.githubusercontent.com/24279964/36191279-8e3d2f7a-1171-11e8-9299-184441b02387.png)

but when i resized application window, i saw both imageboxes turn into purple.
i think this not creating a new instance of img and affects source image too.

**Comment by ASHIT-AXAR** [comment]
and how to resize Controls? (for ex: Button)
i set width and height but nothing changed.
i also called parent ```d registerMovement ``` after that, but no effect.

**Comment by adamdruppe** [comment]
I just pushed a commit that fixes the updateSprite function, which fixes your issue. Though... it still isn't quite right.

So when you do that `auto m = img;` indeed it is not a new instance. So below, you change the existing image. But inside the image box is the `Sprite` instance. This is a copy of the image optimized for display on the window. Before, it would copy it again on every draw (bug). Now it is fixed to just copy once when necessary, so you get two independent sprites showing a snapshot of the image when you set it - good for your use.

But if you do want separate `MemoryImage`s, well, I can just add a `clone` function to the interface, I'll do that soon. But you can also do it yourself... MemoryImage is a base class for IndexedImage and TrueColorImage, so you can cast to of them and get direct access to the pixel memory, and create a new one to clone into.

Let me just write the method then i'll show you the diff so you get it.

on resizing that is actually tricky because of the automatic layout. I'll write a bit about that soon. (BTW the main reason minigui.d isn't officially "released" yet, in that i don't promote it much in public, is because I haven't written all the documentation yet! I still might change part of the interface too, but none of that should be a big deal for you to fix in your code if I do, and also the text boxes are buggy on Linux. but on Windows all is good)

Anyway I'll get back to you soon....

**Comment by adamdruppe** [comment]
Here's the code for clone: https://github.com/adamdruppe/arsd/commit/c1317f932c9591ea08597aaea1bc030cd41cd7b2

so now you can `auto m = img.clone();`

That pattern I used there is somewhat common OOP in D thing. Lots of D articles go on and on about templates and ranges, but D's classes are pretty excellent too. Of course, OOP is well-known, so you can read articles about it from Java and C# and basically C++ too and get to know it, so we don't strictly need D-specific articles on it, but the clone method in the interface there returns the interface. Then each child class returns an instance of itself.

When called from the interface, the static type is still the interface, though the dynamic type is still the specific class (and thus you can `cast(TrueColorImage)` back to it if you want), and if called from the child class, you get that static type too. This is all part of D's implementation of the Liskov substitution principle. But anyway, each overridden function just returns its own type, copies its own methods, and boom it works.

Another background fact... why does MemoryImage have separate TrueColor and Indexed classes? From my docs:

> Why are they separate classes? I think the operations on the two of them are necessarily different. There's a whole bunch of operations that only really work on truecolor (blurs, gradients), and a few that only work on indexed images (palette swaps).
>
> Even putpixel is pretty different. On indexed, it is a palette entry's index number. On truecolor, it is the actual color.

so they just aren't quite compatible, but as you found, the getPixel and setPixel methods can work on either, and you can also force with `getAsTrueColorImage` http://dpldocs.info/experimental-docs/arsd.color.MemoryImage.getAsTrueColorImage.html

The reason `readPng` returns the interface is just that png files can be true color or indexed, and it doesn't know at compile time what kind of files it will open. Of course, you don't *need* to know this - your usage is already pretty effective! But just in case you were curious about the background info.

**Comment by adamdruppe** [comment]
> and how to resize Controls? 

So you can subclass it and set a maxWidth and maxHeight, or nest it inside a `StaticLayout`. Taking your code:

        // layout to hold buttons
        auto hlButton = new HorizontalLayout(window);
        // buttons
        auto slo = new StaticLayout(hlButton);
        auto btnFilter = new Button("Filter", slo);
        btnFilter.width = 230;
        btnFilter.height = 100;
        btnFilter.x = 30;
        btnFilter.y = 30;
        auto btnCancel = new Button("Cancel", hlButton);

So I put the `StaticLayout` inside the `HorizontalLayout` you made, then the `Button` goes inside `StaticLayout`.

The static layout itself gets positioned and sized automatically, but then its contents inside are all manually positioned. This means you can set width/height/x/y on the button inside and it will be respected instead of being overwritten by the automatic sizer.

If you want to do something custom, you can also subclass `Layout` and implement your own `recomputeChildLayout` (you can see that's what `StaticLayout` does; it is a 9 line class to just call the child functions without changing their values. Normally, `recomputeChildLayout` will loop through the children, position them, and then call the child.recomputeChildLayout to propagate. I might change this implementation later though, I'm not 100% happy with it yet, but that's how it works right now)

Anyway, with the sample code above, you can delete the lines that set width and height and see a button's default size: it is sized for its label.

**Comment by ASHIT-AXAR** [comment]
thank you adam. it is getting better.

![gui3](https://user-images.githubusercontent.com/24279964/36277235-91dbece0-12a5-11e8-8aa2-db73e1a941ae.png)

fortunately the library is simple and straightforward. 
i gonna try to add something like `SplitLayout` 
when it's ready, i need you to review that.

**Comment by adamdruppe** [comment]
What's the blue box there? Did you make a larger static layout thing or is there some bug in the overlapping?

**Comment by ASHIT-AXAR** [comment]
hello, no it's not a bug. i just set backgroundColor to see areas.
a `TextLabel`
a `StaticLayout (backgroundColor = Color.blue)` for the buttons
a `HorizontalLayout` for the imageboxes

TextLabel height is as its text.
StaticLayout and HorizontalLayout divided (default) the remaining space that caused crop the images

no problem. i need to interact more with Layouts to get familiar the behavior.
sorry for taking your time with this little things, but i'll need a `OpenFileDialog` soon  ![emoji-dandon-32](https://user-images.githubusercontent.com/24279964/36308190-cb0ab4d0-1334-11e8-92bd-291a669739db.png)

**Comment by adamdruppe** [comment]
so the docs aren't done but there's some of them up:
http://dpldocs.info/experimental-docs/arsd.minigui.html#functions

And, of course, there you see [getOpenFileName](http://dpldocs.info/experimental-docs/arsd.minigui.getOpenFileName.html) which takes a delegate for when the user hits OK - it passes the filename to that.

So teh call looks like

```
     getOpenfileName((string name) {
          // you can now open the file "name"
    });
```

On the user side, it pops up the standard Windows dialog box. The function MIGHT block. On Windows, it does, on Linux, it doesn't. That's why it does the async delegate callback instead of just returning the string directly. (I will probably change that sometime too but for now this works.)


And don't worry about asking this stuff! It is giving me an excuse to type up some explanations of this library. Maybe I will type up the fancy auto-menus and dialogs in a bit....

**Comment by adamdruppe** [comment]
Here's the test code for the newest feature... maybe just run it and see if you can figure it out:

```
import arsd.minigui;

struct Info {
	string name;
	string email;
}

class MyWindow : MainWindow {
	this() {
		super();
		setMenuAndToolbarFromAnnotatedCode(this);
		statusTip = "gnarley";
		textEdit = new TextEdit(this);
		auto hl = new HorizontalLayout(this);
		auto btn = new Button("test", hl);
		auto btn2 = new Button("test", hl);

		btn.addEventListener("click", () {
			messageBox("You clicked");
		});

		btn2.addEventListener(EventType.triggered, () {
			dialog!Info((info) {
				import std.conv;
				textEdit.content = to!string(info);
			});
		});
	}

	TextEdit textEdit;

	@menu("File") {
		@toolbar("")
		@icon(GenericIcons.New)
		@accelerator("Ctrl+Shift+N")
		void New() {
			textEdit.content = "";
		}
		@toolbar("")
		@icon(GenericIcons.Open)
		@accelerator("Ctrl+O")
		void Open() {
			getOpenFileName( (string s) {
				import std.file;
				textEdit.content = (readText(s));
			} );
		}
		@toolbar("")
		@icon(GenericIcons.Save)
		void Save() @accelerator("Ctrl+S") { getSaveFileName( (string s) {} ); }
		void SaveAs() {}
		@seperator
		void Exit() @accelerator("Alt+F4") { this.close(); }
	}

	@menu("Edit") {
		@toolbar("")
		@icon(GenericIcons.Undo)
		@accelerator("Ctrl+Z")
		void Undo() {}
		@toolbar("")
		@icon(GenericIcons.Redo)
		@accelerator("Ctrl+R")
		void Redo() {}
		@seperator
		@toolbar("")
		@icon(GenericIcons.Cut)
		@accelerator("Ctrl+X")
		void Cut() {}
		@toolbar("")
		@icon(GenericIcons.Copy)
		@accelerator("Ctrl+C")
		void Copy() {}
		@toolbar("")
		@icon(GenericIcons.Paste)
		@accelerator("Ctrl+V")
		void Paste() {}
	}

	@menu("Help") {
		@accelerator("F1")
		void Topics() {}
		@seperator
		void About() {}
	}
}

void main() {
	auto window = new MyWindow();
	window.loop();
}
```


So the idea here is to make it slap together some gui stuff using D's ct reflection. The `dialog` function, seen here when you click button 2, reflects on a struct and creates a dialog box to fill in its members automatically.

The setMenuAndToolbarFromAnnotatedCode(this); line makes it look at the class for `@menu`  things to build a menu out... the `@toolbar` tells it which toolbar to place it in, you can set icons and keyboard shortcuts too.

Of course, in this test example, there are so many `@whatevers` that you can barely see the function... but when the user hits the toolbar icon or the menu item, it just automatically calls the given function.

I'm still working on this stuff (I usually do this while trapped on an airplane and I'm not too sick feeling to pull the laptop out... so it moves slowly) and it is subject to change too but I'm already pretty happy with it. For slapping together a quick window that needs basic data forms it makes the code a lot shorter.

BTW that's also why the layouts are automatic by default - i want short code for quick windows.

**Comment by ASHIT-AXAR** [comment]
> And don't worry about asking this stuff!

![emoji-mehrabun-32](https://user-images.githubusercontent.com/24279964/36345573-871e0aba-1442-11e8-9715-240301320b8f.png)

> And, of course, there you see getOpenFileName which takes a delegate for when the user hits OK - it passes the filename to that.

oh, when i saw color_dialog in minigui_addons folder i thought only it is implemented. ![emoji-khejalat-32](https://user-images.githubusercontent.com/24279964/36345595-120bbb54-1443-11e8-92a3-0e04c6e2ec0c.png)

> Here's the test code for the newest feature... maybe just run it and see if you can figure it out:

it is not compiling. giving the following error:

```
D:\Dproj\gui3>dmd menu.d arsd/simpledisplay.d arsd/color.d arsd/minigui.d -L/sub
system:windows:5.0
menu.d(32): Error: function expected before (), not module menu of type void
menu.d(56): Error: function expected before (), not module menu of type void
menu.d(80): Error: function expected before (), not module menu of type void
```

**Comment by adamdruppe** [comment]
That's actually because you called it menu.d... just rename the file to something else, or give it a module declaration like `module mytest.menu;` at the top of the sample (I should add that to all the examples...).

The implicit module name of `menu` there conflicts with the imported symbol `menu` from the library. This is why I usually recommend to ALWAYS use a module name of at least two pieces (like `foo.bar` instead of just `foo`)... but I don't follow that myself on small examples....

**Comment by ASHIT-AXAR** [comment]
just worked. very well ![emoji-shegeft-32](https://user-images.githubusercontent.com/24279964/36345755-0bf3c2ea-1446-11e8-9275-534cb86c9d2b.png)

opendialog work only on files (what about selecting a folder?)

**Comment by adamdruppe** [comment]
Selecting a folder is a different function on the underlying Windows API. I haven't implemented it yet... actually, I haven't implemented many of the newer ones at all yet because Windows wants you to use COM interfaces, and I  just haven't finished that code, so that world of Windows functions isn't quite opened up to easy use yet..

**Comment by ASHIT-AXAR** [comment]
yes, folder dialog is a rather case. i don't think i need one in near future. 
thank you.

**Comment by adamdruppe** [comment]
btw here is what the example program looks like on my linux box if anyone is curious

![minigui on linux](http://arsdnet.net/onlinux.png)

The window border, of course, is my desktop, but the window contents are all minigui.d's 100% custom widget implementations. On Windows, minigui uses standard functions. But on Linux, I don't like the other gui toolkits very much for various reasons, so I am making my own in here. You can also use the custom stuff on Windows with `-version=custom_widgets`, but you probably shouldn't cuz it sucks lol.

that said, if someone were to send me a gtkd backend PR for minigui, I'd merge it.

**Comment by ASHIT-AXAR** [comment]
i am curious what is your OS ?
i am using win7. lately i was searching for alternative on the internet i found TrueOS(a FreeBSD derivative) but unable to boot. now i have win7 and ubuntu (dualboot) . 
linux needs a active connection for anything to do ![emoji-khasteh-32](https://user-images.githubusercontent.com/24279964/36345917-8ee39786-1449-11e8-91af-06af846052cd.png)
that is why i am happy with win7.

**Comment by adamdruppe** [comment]
I use (a pretty heavily customized) slackware linux. It is one of the older-style linuxes.
