### ISSUE TITLE
http://code.dlang.org/packages/arsd-official

### ISSUE THREAD

**Issue by EmTee70** [adamdruppe/arsd#145]
arsd-official:nanovega is not listed, and so 
dub error:
Non-optional dependency arsd-official:nanovega 
? 
I know you are no big fan of DUB, but ... :-)
I am at Ubuntu 17.10 64 Bit now.  After installing: 
sudo apt install libxext-dev
sudo apt install libgl1-mesa-dev
sudo apt install libglu1-mesa-dev
sudo apt install libglc-dev 
sudo apt install libfreetype6-dev
sudo apt install libfreetype6
sudo apt install libx11-dev

(probably different order...)  I still get an error when trying to build the example with dub:
...
Linking...
/usr/bin/dmd -of.dub/build/application-debug-linux.posix-x86_64-dmd_2079-0295D248A438B2DB092B66CD495C6DEE/nanovega .dub/build/application-debug-linux.posix-x86_64-dmd_2079-0295D248A438B2DB092B66CD495C6DEE/nanovega.o -L--no-as-needed -L-lX11 -L-lXext -L-lGL -L-lGLU -g

source/nanovega.d:8842: Fehler: undefined reference to 'FT_Init_FreeType'
source/nanovega.d:8857: Fehler: undefined reference to 'FT_New_Memory_Face'
source/nanovega.d:8944: Fehler: undefined reference to 'FT_Set_Pixel_Sizes'
source/nanovega.d:8945: Fehler: undefined reference to 'FT_Get_Kerning'
source/nanovega.d:9058: Fehler: undefined reference to 'FT_Load_Glyph'
source/nanovega.d:9066: Fehler: undefined reference to 'FT_Outline_Get_CBox'
source/nanovega.d:9068: Fehler: undefined reference to 'FT_Outline_Decompose'
source/nanovega.d:9084: Fehler: undefined reference to 'FT_Load_Glyph'
source/nanovega.d:9092: Fehler: undefined reference to 'FT_Outline_Get_CBox'
source/nanovega.d:9094: Fehler: undefined reference to 'FT_Outline_Decompose'
source/nanovega.d:10031: Fehler: undefined reference to 'FcNameParse'
source/nanovega.d:10034: Fehler: undefined reference to 'FcConfigSubstitute'
source/nanovega.d:10035: Fehler: undefined reference to 'FcDefaultSubstitute'
source/nanovega.d:10038: Fehler: undefined reference to 'FcFontMatch'
source/nanovega.d:10042: Fehler: undefined reference to 'FcPatternGetString'
source/nanovega.d:10040: Fehler: undefined reference to 'FcPatternDestroy'
source/nanovega.d:10033: Fehler: undefined reference to 'FcPatternDestroy'
source/nanovega.d:13555: Fehler: undefined reference to 'FcInit'
source/nanovega.d:8872: Fehler: undefined reference to 'FT_Get_Char_Index'
source/nanovega.d:8881: Fehler: undefined reference to 'FT_Set_Pixel_Sizes'
source/nanovega.d:8883: Fehler: undefined reference to 'FT_Load_Glyph'
source/nanovega.d:8885: Fehler: undefined reference to 'FT_Get_Advance'
source/nanovega.d:9106: Fehler: undefined reference to 'FT_Load_Glyph'
source/nanovega.d:9112: Fehler: undefined reference to 'FT_Outline_Get_CBox'

Any hint?

**Comment by ASHIT-AXAR** [comment]
are you able to run the example with dmd ?
i tried to run with dmd and i get some errors.

```
D:\Dproj\nvg>dmd nvg.d arsd/simpledisplay.d arsd/nanovega.d arsd/ttf.d arsd/colo
r.d -L/subsystem:windows:5.0
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
nvg.obj(nvg)
 Error 42: Symbol Undefined _D4arsd5image12__ModuleInfoZ
Error: linker exited with status 1
```
i dont know if that refer to `arsd/image`. but when i include that, it just shows a couple more errors.

**Comment by adamdruppe** [comment]
On Fri, Mar 09, 2018 at 05:40:07AM -0800, ASHIT-AXAR wrote:
> are you able to run the example with dmd ?
> i tried to run with dmd and i get some errors.

If you have image.d downloaded and in the path, it requires it and its dependencies too:

image.d, png.d, targa.d, bmp.d, jpeg.d, pcx.d, dds.d

all required if image.d exists. So add them ALL to your build command with dmd.


Alternatively, use the new `dmd -i` option if you are on the latest version and it will do all that for you. Or `rdmd` does the same.


Or, of course, you can take image.d OUT of the search area so dmd can't see it, then it will no longer be required. Change your current directory, or delete it, move it, rename it, whatever, and it will no longer be compiled in (you'll lose image file loading support though).


When I write the instructions to "download files X", I often assume they are the ONLY files you actually download. If you get more, the others may be compiled in to add additional features and thus may need to be passed too to avoid the linker error because the compiler thinks the module is available but the linker doesn't know unless you explicitly pass them.

**Comment by adamdruppe** [comment]
> /usr/bin/dmd -of.dub/build/application-debug-linux.posix-x86_64-dmd_2079-0295D248A438B2DB092B66CD495C6DEE/nanovega .dub/build/application-debug-linux.posix-x86_64-dmd_2079-0295D248A438B2DB092B66CD495C6DEE/nanovega.o -L--no-as-needed -L-lX11 -L-lXext -L-lGL -L-lGLU -g

Dub didn't seem to link in fontconfig and freetype. It probably needs to be told explicitly in its config file what plain dmd already knows from the source code. (seriously what is dub's purpose in even existing when we already have dmd?)

**Comment by EmTee70** [comment]
Thank you!
> seriously what is dub's purpose in even existing when we already have dmd?
As you will have noticed, I am still in the infancy of using D, I don't know :-)
I thought using dub not dmd give you a little overhead but keeps things better managed? 
Coming from using vibe.d - for some internals - I was quite satisfied with the result, (fast webservices).
There has been a lot of discussion recently about using a build system / using dub. Do you think there  should be anything 'like' dub but better?

**Comment by adamdruppe** [comment]
On Fri, Mar 09, 2018 at 07:07:17AM -0800, EmTee70 wrote:
> As you will have noticed, I am still in the infancy of using D, I don't know :-)

I'm fixing the dub.json file now, I think I have it, just gotta test on Windows before I release...

> I thought using dub not dmd give you a little overhead but keeps things better managed? 

The big things dub adds over dmd are:

1) automatic package downloading
2) package version selection

But on the other hand, you have to tell it all about this stuff and it only works on a new dub package level, not the module level like the language itself, and it doesn't use the information available in the source file to figure out dependencies, libraries, etc. You have to tell it this in the separate dub.json file. Now, there is a reason for this: versioning and automatic downloading (the two benefits bring this cost with it). But I'm still not a fan.

My code tends to be written as few-dependencies modules with on-demand expansion. For example, dom.d works by itself unless you call one of the character set conversion functions. Then it depends on characterencodings.d too. But if you don't call that function, you don't pay for it, and if you do, you just add the module - no additional configuration needed.

Similarly, nanovega (actually written by ketmar btw, I'm more the publisher than the author here) checks if you downloaded the image format support files. If you have, it tries to use them to add image support. If not, it doesn't and that feature is just not compiled in.

Of course though, if you download them all and don't pass them to the compiler (or use dmd -i or rdmd which handle this automatically - ketmar swears by rdmd btw), it will THINK they are available and try to use them, but then give linker errors. So that's the downside to it.

dub can't really do this optional dependency thing because if it doesn't see a file downloaded, it just wants to download it, and it can't know what you actually used in your source since it doesn't look at the source! Instead, it uses dub.json "configurations" so you tell it which config you need in your own config file. It works, it just is different than mine and thus causes a lot of friction.

I also get annoyed with dub wrapping so many dmd commands and renaming them. So some sources tell you to use "dmd -J", but if you use dub, it is now "stringImportPaths" in dub.json. Ugh. But again, it is slightly different for ldc and gdc as well so I understand why they did it... it just annoys me.

(and speaking of layers, code.dlang.org does down a lot, and it brings all dub users down with it. with my preferred strategy, you just keep a copy of my files around. And you can easily edit them to suit your needs!)

> Coming from using vibe.d - for some internals - I was quite satisfied with the result, (fast webservices).

my cgi.d does fast webservices without any dependencies :P

> There has been a lot of discussion recently about using a build system / using dub. Do you think there  should be anything 'like' dub but better?

I don't hate the idea of downloading module versions on demand. But I also don't think it is all that beneficial.

When you're using a library, how often is the trouble in just clicking the link on the website and hitting "save as"? And maybe periodically updating the branch for bug fixes etc? It is a tiny fraction of programming effort, yet we spend soooooooooooo much time on it.

Then the mess of dependencies is made so "easy" we end up with highly coupled webs of pain that can be taken down across the whole internet when some trivial 10 line left-pad thing has an outage.

More like "outrage" am I right?

**Comment by adamdruppe** [comment]
And btw the whole version thing doesn't work for me anyway because I work on the module level, not the dub package level. dub doesn't support versioning individual files, or even subpackages (which I use to kinda hack my files into dub). You have to version git repos... which is an awful lot of overhead.

So I gain nothing from dub, and have to do a fair chunk of work to keep it working on my stuff.

**Comment by adamdruppe** [comment]
ok folks, I updated dub.json and since I think this *might* be a breaking change depending on just how dub works, I also upped the version number to 2.0.

http://code.dlang.org/packages/arsd-official

though i also tagged it 1.4 cuz i really have no clue (and that it why semver doesn't work in practice!!). I didn't break the code tho, just changed the dependency tree of the json so it shouldn't actually break anything... heck my first instinct was to call it 1.3.1 but since it has a new subpackage...

Anyway if you request the new version in your dub config we should be good to go. Let me know....

**Comment by adamdruppe** [comment]
@ASHIT-AXAR so if you are using dmd, pass the images to it. If you are using dub, I just updated the config to include the images package as a dependency anyway.

**Comment by EmTee70** [comment]
Thank you Adam, now it works with dub and without :-)
I will take an additional look to your cgi.d maybe it gives the better tool for my "microservices".
The long error was caused by mixing dub with nanovega.d in my source directory.

**Comment by ASHIT-AXAR** [comment]
@adamdruppe 
thank you adam. i didn't know existing extra modules in the working directory may affect compiling.
i deleted unused modules and it is just fine now.
i prefer to use dmd. downloading required files myself (in this case the whole archive, due to it's very low size), everything in a single directory. (deleting the directory if needed, and starting fresh)

and the result (it looks like GradientBrush in WPF)
![untitled](https://user-images.githubusercontent.com/24279964/37229600-bf653d14-23f9-11e8-831a-db2bf9710a6c.png)

**Comment by EmTee70** [comment]
Thank you again.
