### ISSUE TITLE
cgi: listening-host for embedded_httpd

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#175]
There is a comment in source code that listening-host is not implemented for embedded_httpd
https://github.com/adamdruppe/arsd/blob/master/cgi.d#L490
Is this still true or is the comment outdated?

There are also some fixed usage of port 8085 
https://github.com/adamdruppe/arsd/blob/master/cgi.d#L2756
https://github.com/adamdruppe/arsd/blob/master/cgi.d#L2881
Is this correct, or should the value from --port be used here?

**Comment by adamdruppe** [comment]
On Thu, Nov 15, 2018 at 10:36:09PM -0800, andre2007 wrote:
> There is a comment in source code that listening-host is not implemented for embedded_httpd

that comment is false, it is now implemented.

> There are also some fixed usage of port 8085 
> https://github.com/adamdruppe/arsd/blob/master/cgi.d#L2756
> https://github.com/adamdruppe/arsd/blob/master/cgi.d#L2881
> Is this correct, or should the value from --port be used here? 

that's the default argument if you don't pass a --port, but the function
there looks it up if you did. So it works (and I use it locally to run
several things at once).


BTW some new stuff is coming to cgi.d .... eventually. My new comments
outline the ideas. Among them are:

1) a websocket helper thread/process that does event based i/o and passes
the socket off to it, to handle more persistent connections without using
up the main worker processes/threads. It will do broadcast event stuff (and
maybe the js SSE stuff too.)

2) a session helper process, automatically spawning when needed, to just store
some data. web.d has a few options for these (files, memory, and signed
cookies) but I want to start phasing the old web.d out...

3) and bring over the automatic object stuff the old web.d has right into cgi.d
as an opt-in template.


Don't hold your breath on any of this, I am in no huge rush (in fact, I just
started a new web.d based project recently anyway) but it is some future
directions. Otherwise though I am pretty happy with its stability and will
just do some performance tweaks as time permits.

I will also do more docs eventually.

**Comment by andre2007** [comment]
Thanks a lot. The additions you plan looks great.
As my questions are solved, I close this issue.
