### ISSUE TITLE
terrible performance

### ISSUE THREAD

**Issue by Aphexus** [adamdruppe/arsd#179]
Without doing anything but displaying the fps I get max around 40. It should be upwards of thousands.

This is windows. Can you do some basic profile test of a very bare bones test case to see the max frame rate? My code is simply

			frames++;
			if ((MonoTime.currTime - startTime).total!"seconds" > 1)
			{
				fps = frames;
				frames = 1;
				startTime = MonoTime.currTime;				
			}
			DrawString(to!string(fps), 60, 50, 50, 255, 255, 255);

Maybe the drawing code needs to run in a separate thread? (can't remember I'm running it off the main thread or not)

**Comment by adamdruppe** [comment]
Can you post a complete program that I can actually run?

**Comment by Aphexus** [comment]
That is essentially the complete program. I do nothing but call that code in the rendering function/event loop and nothing else.

Surely you have a test project and you can simply do some fps testing on it and at least verify that it is on my end?  My code is a bit more complex because I've abstracted some stuff around your code so I'd have to send a lot more... but none of the abstract has anything to do with graphics except DrawString... but you could just display to console or whatever.

If your test programs doesn't get very high fps then it means it's in your library somewhere. I've looked at the event loop and there is a sleep and the event handling is a bit complex. 

If you get get more than a few hundred fps on rendering nothing then it means it's your library. If you can get thousands then it is on my end.

What it looks like is that you are processing a lot of event code when it probably doesn't need to be run so often... or it is running at the speed the message loop is being called, in which case I guess putting the rendering code in it's own thread would be more appropriate.

**Comment by adamdruppe** [comment]
It depends on your OS and graphics drivers if you are using the built-in timer ticker, but on many systems (including my Windows laptop, which gets 65) it maxes out at about 60 ticks per second, and on others, it will max out at 1000.

If you want more than that (which is worthless btw unless you have extraordinary hardware), you will have to do a different loop (put 0 for the timeout and postEvent instead).

Using postEvent, it maxes out at 1800 on my Linux box.... and a whopping 160,000 on my Windows box (maxing out the CPU).

```
import arsd.simpledisplay;
import std.datetime;
import std.stdio;

class Frame {}

void main() {
	int frames = 0;
	int fps;
	auto window = new SimpleWindow();
	auto startTime = MonoTime.currTime;

	auto frame = new Frame;

	window.addEventListener((Frame trigger) {
		frames++;
		if ((MonoTime.currTime - startTime).total!"seconds" >= 1)
		{
			fps = frames;
		writeln(fps);
			frames = 0;
			startTime = MonoTime.currTime;
		}
		window.postEvent(frame);
	});

	window.postEvent(frame);

	window.eventLoop(0);
}
```

But you should NOT do that since it burns cpu power needlessly! But it should stay responsive to user input as long as your event runner isn't too time consuming, and if you want to put your own throttling on it, you can use it as a starting point.
