### ISSUE TITLE
Free function htmlToText, wantWordWrap argument

### ISSUE THREAD

**Issue by wilsonjord** [adamdruppe/arsd#236]
It doesn't seem like the wantWordWrap passed properly to the convert function.

**Comment by adamdruppe** [comment]
ah yes indeed, fixed. I think the only time I have used that is in my email.d's automatic text fallback given just html and I use just default args there anyway and never noticed!

**Comment by adamdruppe** [comment]
BTW the htmltotext generator is VERY heavily biased for my reading my html email in the terminal. There's some things that could be nicer in theory with semantic html, but with the ugly emails I get ended up being even worse. That's why the table thing is the way it is for example, it was more legible to just output them as a list of blocks than to try to render them.

**Comment by wilsonjord** [comment]
Great thanks for the speedy fix. I was testing out the function as a way to almost "minify" html source, although I suspect what I really want is just plain text with some idea of the actual html structure left in somehow, so I'll probably need to modify it somewhat.

**Comment by adamdruppe** [comment]
The dom.d library has a `Element.stripOut()` that might be helpful for you.

So you could potentially go through and trip out all the html stuff you don't care about while keeping the rest. I've used that for security whitelisting too (in the html.d lib but that one isn't as well maintained since I haven't actually used it for a long time).

That's basically what the htmlToText thing does so its implementation might be a good starting point for you too.

**Comment by wilsonjord** [comment]
Thank, will check out.
