### ISSUE TITLE
How to save the arsd's documents 

### ISSUE THREAD

**Issue by WangWei90** [adamdruppe/arsd#243]
Thank you for the great library, all in one place :)
Feel free to close it if it is not related.

I am a Chinese Pdoc, I want to save arsd's documents locally (e.g. https://arsd-official.dpldocs.info/arsd.html) due to internet connection problems. I also want to store the std documents locally (http://dpldocs.info/experimental-docs/std.html).

What should I do? The international internet connection is very very slow or not reachable.

**Comment by adamdruppe** [comment]
On Fri, Feb 28, 2020 at 11:43:34PM -0800, Walker Wang wrote:
> What should I do? The international internet connection is very very slow or not reachable.

I was actually working on adding compression code to my local
thing yesterday that can pack all those docs into about a ~4 MB
download. Then I'll make a little web server you can download to
serve them up to a browser. Or you could uncompress with my custom
program to regular static html.

Or I can make you up a standard .zip or .tar.gz file that you simply
unpack locally and open the html in your browser. Uncompressed the
whole thing over 50 MB though. (it compresses very well because of
how much duplication there is in the static html for a compressor
to deflate).

Just my custom compressor does 1/2 the size of tar.gz,  1/5 the size
of zip :P (.tar.xz is smaller yet but it is significantly slower)


But still, later today I'll make all the options available so I'll
get back to you soon!

**Comment by WangWei90** [comment]
You are awesome, Thank you!

I don't know anything about the web server. However, if you could write some guidance, I think I will manage to use this server (at the same time start getting my hand dirty on the "web" thing ^_^).

As for the file size, I don't matter since this great documentation will just occupy a litter space on my hard disk. It justifies. (I prefer zip since I am on windows 10)

Really really appreciate your work here!

**Comment by adamdruppe** [comment]
I haven't finished my other thing yet so I just made oyu a zip for now. Let me know once you have it because I don't want to keep it up forever. http://dpldocs.info/packed_docs.zip

has phobos, druntime, and arsd generated html inside, also with annotated source. you can just open the html files normally and it will pop up a browser. All should work, including search, though it may be a little slow. Decompresses to 350 MB!

**Comment by WangWei90** [comment]
Hello adam, thank you for the quick response~

I have downloaded your copy, and It works! e.g. searching (packed_docs/search-results.html) , arsd contents (packed_docs/arsd.html), std (packed_docs/std.html) et al. I will look into other files but I am not familiar with them now :)

**Comment by adamdruppe** [comment]
You should be ok opening basically any file in there as your starting point (I did do search wrong so the bar up top assumes you are on my server... oops, but indeed you found the file to use offline anyway :) ) and just click around links to get to what you want.

**Comment by WangWei90** [comment]
I am comfortable with the offline documents now. I am closing this issue.

Thank you again.
