### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'crypto.lib'?

### ISSUE THREAD

**Issue by mingwugmail** [adamdruppe/arsd#255]
```
$ grep arsd dub.json
                "arsd-official": "~>7.2.0",

$ dub.exe --version
DUB version 1.21.0, built on May 11 2020

$ dmd.exe --version
DMD64 D Compiler v2.092.0-dirty
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

So where I can get the 'crypto.lib'?  on Windows 10?

Thanks.

**Comment by mingwugmail** [comment]
found this one:

AppData/Local/dub/packages/vibe-d-0.8.6/vibe-d/lib/win-amd64/libcrypto.lib

but not under:
AppData/Local/dub/packages/arsd-official-7.2.0/

**Comment by mingwugmail** [comment]
and this error:

LINK : fatal error LNK1104: cannot open file 'ssl.lib'

**Comment by mingwugmail** [comment]
LINK : fatal error LNK1104: cannot open file 'libmysql.lib'

**Comment by mingwugmail** [comment]
only found: 

AppData/Local/dub/packages/arsd-official-7.2.0/arsd-official/arsd-official_mysql.lib

but the name doesn't match.

**Comment by mingwugmail** [comment]
LINK : fatal error LNK1104: cannot open file 'pq.lib'

**Comment by mingwugmail** [comment]
/AppData/Local/dub$ find .  -name '*pq*lib'
# nothing showed up

**Comment by adamdruppe** [comment]
On Tue, May 19, 2020 at 11:54:16PM -0700, mingwugmail wrote:
>                 "arsd-official": "~>7.2.0",

Never use the top-level package. Only use the individual subpackage you
actually need. Dub doesn't treat it well as a whole block...

**Comment by adamdruppe** [comment]
so for these:

crypto.lib and ssl.lib (not necessary in my newest version but not yet pushed so that doesn't help you) are part of OpenSSL. openssl is used by the http libs.

mysql.lib is the MySQL C library.

pq.lib is the PostgreSQL C library.


Each of those are downloaded from their own websites as part of installing those platforms. But if you aren't using them, don't do that! Just use the other subpackage for your specific goal instead.

**Comment by mingwugmail** [comment]
Thanks. Yes, that solve my current problem.

But, I think those libraries should come together with the package, so the library user will have a more smooth build process (suppose in a  auto-build system).

Those libraries are quite mature & stable, nobody cares if it's old; and even old is better than missing.  If for any other reason (e.g. external licensing or permission issue) that the library cannot be distributed with the package, then can we update the readme remind the user to download them manually (better provide external url, or automate by dub).

For the library provided, e.g.
AppData/Local/dub/packages/arsd-official-7.2.0/arsd-official/arsd-official_mysql.lib

we should make the filename and the entry in the dub.json matches.

Thanks again for maintaining this package, I just want to make its user experience even better.

**Comment by adamdruppe** [comment]
On Wed, May 20, 2020 at 10:26:25AM -0700, mingwugmail wrote:
> But, I think those libraries should come together with the package, so the library user will have a more smooth build process (suppose in a  auto-build system).

The .libs aren't what matter though, they are just a minimal interface
to the dll, which is an interface to the database server. (OpenSSL
could prolly be included though, at least I can put up a direct download
link).

So either way, they have to install something. I can add a more explicit
note to the readme though. I'll include that in the next release.

> For the library provided, e.g.
> AppData/Local/dub/packages/arsd-official-7.2.0/arsd-official/arsd-official_mysql.lib

I think that's generated by dub just to cache that module's build since
I don't provide such a thing myself.

**Comment by adamdruppe** [comment]
The crypto.lib is now dynamically loaded and doesn't need the packaged thing so gonna close htis.
