### ISSUE TITLE
jni.d alternative

### ISSUE THREAD

**Issue by System0x20** [adamdruppe/arsd#265]
This module helps a lot
But its outdated as hell (Java 6)
do you know any newer modules?

**Comment by adamdruppe** [comment]
On Fri, Oct 09, 2020 at 04:46:27AM -0700, Nader Jafari wrote:
> But its outdated as hell (Java 6)

There's been only one change to JNI since then, a new function
called GetModule, added in version 9.

I added it just now, but it doesn't really affect this lib.

The big thing you can try is to make a copy of jni.d for yourself
and change the JNI_VERSION_DESIRED value to 0x000a0000 instead of the
VERSION_6 it is now. That will give you the newest version it offers.
idk if it would change anything.


Let me know if there's specific problems you have.

**Comment by adamdruppe** [comment]
BTW if it does change things let me know about that too since editing that value from code instead of modifying the source is something maybe worth trying, or it can just ask for newest and walk down until it gets one that works.
