### ISSUE TITLE
Minigui: ListWidget

### ISSUE THREAD

**Issue by andre2007** [adamdruppe/arsd#273]
If my understanding is correct, the equivalent to win32 List Box is the ListWidget.
But this widget can only be used by setting a specific version.

The List Box is a very common control. Could you check wheter you can activate it by default. Or if this is not possible, add a dub configuration to make it easier to activate this widget?

**Comment by adamdruppe** [comment]
On Thu, Jan 28, 2021 at 04:59:09AM -0800, andre2007 wrote:
> If my understanding is correct, the equivalent to win32 List Box is the ListWidget.
> But this widget can only be used by setting a specific version.

Yeah, I never got around to implementing it on Windows, only the custom
implementation has it (which I use on Linux but isn't really appropriate
for Windows).

The list widget is fairly complex to do well and I could never be happy
with it. But perhaps a plain text one with a retained list would be good
enough. Just I was looking before about doing a live list thing and it
was too complicated so I put it off and off and off.

I'll see if I can do the simple native one later though.... it might
change again in a future version though because I'd like it to support
options like icons and stuff later too.

**Comment by adamdruppe** [comment]
Well, I think I have this working locally, but I had to refactor some other code in the process and am concerned I broke something... wanna do more testing before I push.

**Comment by adamdruppe** [comment]
well it seems ok, i pushed it, lmk if i broke stuff

**Comment by andre2007** [comment]
Solved
