### ISSUE TITLE
WebSocket ability to set TCP_NODELAY

### ISSUE THREAD

**Issue by CoderNate** [adamdruppe/arsd#366]
Minor thing but it would be cool to be able to get rid of the latency from the Nagle algorithm but the `socket` inside of a WebSocket is private so I can't call `setOption`.  I thought maybe I'd just send an extra Pong message with some dummy bytes in it just to fill the send buffer but it looks like there's a minor bug in `pong` where it doesn't add bytes to the frame until after it's been sent:

https://github.com/adamdruppe/arsd/blob/853835196e8eb2b05c94cf244ee45941a3fdc8f8/http2.d#L4928-L4929

**Comment by adamdruppe** [comment]
whoops that's a silly bug. but yeah the nodelay is really just an oversight, since it handles buffering internally i should have disabled it anyway.

**Comment by adamdruppe** [comment]
see how that commit works for you

**Comment by CoderNate** [comment]
Your turnaround time on issues is amazing. That fixes it. Thanks!

**Comment by adamdruppe** [comment]
Some of these things are just trivial oversights I forgot about or didn't test right. Then a bunch of things are on my list and I've thought about them before and laid groundwork for it but never finished (each individual thing can be quick but when I have hundreds of them in between other responsibilities there's a prioritization bump you get by nagging me about it so I can do it quick when otherwise I wouldn't have gotten around to it for maybe a couple years.)

But yeah if things come up just let me know, if I can't turn it around I'll still at least always try to answer same day (or next day if it comes in when I'm already in bed).
