### ISSUE TITLE
arsd.script    "Var v1={'abc ': 1};" is not supported. 

### ISSUE THREAD

**Issue by sdvcn** [adamdruppe/arsd#420]
```
unittest {
	interpret(`var v1 = {'abc':1};`);
}
```

> 
"\script.d(3569): 1: Parse error, unexpected **:**"

**Comment by adamdruppe** [comment]
Yeah that's actually intentional - it conflicted with the D syntax for anonymous functions so i left it out.

I used a more D-compatible

```
var v1 = json!q{'abc':1};
```

instead... which  is kinda ugly and maybe it is time to change this, even in D I'm probably going to change this pretty soon to use an iq{} thing instead.

But if you do that `json!q` prefix rn it will work in script.d. And yeah maybe it is time to revisit this and add it in.

**Comment by sdvcn** [comment]
What version does this interpreter implement?
```
var c1 = new class{};
```

```
class c1
{
    function demo()
    {
        let v = 10;
    }
}
```
None of these can be executed correctly.

**Comment by adamdruppe** [comment]
Version of what? it is a custom language.

**Comment by sdvcn** [comment]
Does this mean that it is only compatible with the syntax, not with ECMAScript?

**Comment by adamdruppe** [comment]
Yeah, it is loosely based on a mix of old Javascript and basic D, but it is its own thing and not compatible with either.
