### ISSUE TITLE
Mysql quey fetchNext is error

### ISSUE THREAD

**Issue by donglei** [adamdruppe/arsd#66]
use mysql.d in my project, just simple select sql, the result is not wanted, why?

code  as follows
foreach(item; db.query("SELECT \*  FROM f_user_key")){
        writeln(item);
    } 
result is
["1", "", "6", ""]
["2", "", "6", ""]

database data is
 2  2   69025f5e6c7dd0c1157e0daf94e9cef5zz  69025f5e6c7dd0c1157e0daf94e9cef5z

**Comment by donglei** [comment]
mysql client version is 5.5.43, success in windows error in debian

**Comment by donglei** [comment]
It fixed! just uint to size_t in mysql.d
size_t* mysql_fetch_lengths(MYSQL_RES*);
string fromCstring(cstring c, size_t len = -1) 
size_t* lengths = mysql_fetch_lengths(result);

**Comment by adamdruppe** [comment]
On Tue, May 19, 2015 at 01:01:12AM -0700, donglei wrote:
> It fixed! just uint to size_t in mysql.d

I don't think that's quite right either, the C function
returns an unsigned long which has a variable size. I
beleive it will have to import core.stdc.config; and return
c_ulong instead of either uint or size_t.


size_t I think will work on 32 bit Windows and both 32 and 64
bit Linux, but break on 64 bit Windows....

**Comment by adamdruppe** [comment]
Does my new commit fix it for you too?

**Comment by donglei** [comment]
It works ok on 64 bit Windows 8.1 with DMD32 D Compiler v2.067.0, Debian 7.8 with DMD64 D Compiler v2.067.1.
It maybe depend on the DMD version.I said that correctly?
