### ISSUE TITLE
Detecting more key events

### ISSUE THREAD

**Issue by zyedidia** [adamdruppe/arsd#79]
It seems like it is only possible to detect normal key events and these "special" key events:
```
escape
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
LeftArrow
RightArrow
UpArrow
DownArrow
Insert
Delete
Home
End
PageUp
PageDown
```

I was wondering if it would be possible to detect more key events such as control-s or control-q. Currently neither of these events are detected at all.

**Comment by adamdruppe** [comment]
On Sun, Mar 13, 2016 at 02:55:15PM -0700, Zachary Yedidia wrote:
> I was wondering if it would be possible to detect more key events such as control-s or control-q. Currently neither of these events are detected at all.

Those are intercepted by the kernel by default and do special things.
You can disable that interception with the command `stty +ixon` in your
shell.

Then the program will see them normally as characters 18 (q) and 20 (s).


The library could perhaps run that command itself but since it is a feature
on another abstraction layer I don't really want to.


There's a lot of other events that happen too. Control+a is sent as character
1 on Posix, ctrl+b is character 2, ctrl+c is intercepted by the kernel (and 
the library redirects it into the UserInterruptionEvent), and many more.

**Comment by zyedidia** [comment]
Thank you for the tip! I'm not really sure what I'm doing, but I fixed my issue by adding the following in the constructor for Terminal:
```
n.c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
n.c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP | INLCR | IGNCR | ICRNL | IXON);
n.c_oflag &= ~OPOST;
n.c_cflag &= ~(CSIZE | PARENB);
n.c_cflag |= CS8;
```
before doing
```
tcsetattr(fdIn, TCSANOW, &n);
```
I think this is what stty does, except with some more flags right?
