### ISSUE TITLE
htmltotext fails to compile

### ISSUE THREAD

**Issue by kookman** [adamdruppe/arsd#80]
Looks like this might not have been used for a while(?) It refers to non-existent property/method "prependText" on Element (in dom.d).

**Comment by adamdruppe** [comment]
On Mon, Mar 28, 2016 at 09:39:39PM -0700, kookman wrote:
> Looks like this might not have been used for a while(?) It refers to non-existent property/method "prependText" on Element (in dom.d). 

Oh yeah, I actually rewrote it a few weeks ago but never pushed
to github.

Try the new version, it doesn't do all exactly the same as the
old version but it is like 10x faster (seriously, the old one was
really poorly written) and covers most the cases.

I use it for reading html emails here and plan to expand eventually
to add more support for other things too - let me know if there's
anything specific you need.

**Comment by kookman** [comment]
Wow that was quick! Thanks. 

I much prefer the recursive design of the new one: definitely cleaner. I also plan to use for HTML email conversion. I've only had a quick browse of the source so far. I won't get to try until the weekend, but will let you know if I see gaps ... or maybe send a PR ;-)

**Comment by adamdruppe** [comment]
I accidentally left some CSS stuff in there, just removed that.

(Yes, I have enough CSS related code snuggled in dom.d that it
can actually apply real-world (if simplified) stylesheets to a
document, with specificity rules too! It doesn't handle everything,
but here I was just thinking about checking things like italic and
color. It worked well in my proof of concept test making it display
the code samples from dpldocs.info with syntax highlighting!)

I might make this configurable in the near future. Right now, it
is just one public function that takes a html string and returns
a text string. With the new class, I plan to start adjusting it so
you can subclass to customize output and set bool switches to turn
on/off different features.

For example, color support could be embedded terminal control strings.
That isn't always appropriate, but is cool when outputting to a linux
terminal. Table support might be toggled. Reading CSS blocks with ::after
might be allowed.

Italic and bold may be output by ascii art, or by terminal control
sequences.

And ultimately, if I do it right, it won't have to return a string. Instead,
you can subclass and just react to events it sees. So then you'll have
a kind of flexible HTML renderer... which I'll make some optional import
backends for terminal and simpledisplay. Throw in a http client (gee, I have
one!) and guess what, we have our own little simple text-mode browser!

Obviously, you wouldn't use that to replace Firefox (that'd be WAY too
big, I want this to still be a reasonably small module), but it could be
reasonable for email viewers, web scrapers, etc. for HTML off the web,
or as a kind of rich text display (and click handling, hopefully) library
for terminal and simpledisplay where you write a html subset to render
instead of issuing all the font commands yourself in code.  


I might also paste it straight into dom.d eventually fyi.


But for now, yeah, I really just want it good enough for email.
