### ISSUE TITLE
Modularize in different packages 

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/arsd#85]
I happen to bump to your repo from time to time and your modules are really cool, but sometimes it's pretty hard to find them. Having them as separate repos and dub packages would definitely help their visibility and probably make it easier for people to use. 

I guess the main problem was the dub was previously not production ready, but maybe the upcoming 1.0 release might be a good opportunity?

**Comment by adamdruppe** [comment]
On Tue, May 17, 2016 at 03:46:48PM -0700, Sebastian Wilzbach wrote:
> I happen to bump to your repo from time to time and your modules are really cool, but sometimes it's pretty hard to find them.

dub's search has been improving, subpackages for example now will bring up the container package on search. Still not on the front page listing, but I think Sonke might be adding that too eventually.

Though I'm barely compatible with dub anyway, since it doesn't support my development flow. Breaking it into different repos would add an annoying amount of overhead - I'd have about 25 repos each with just one or two files each! That seems silly to me, even if I do manage to make it work without breaking my flow (which I think I could actually, subdirectories plus hard links might be able to give a migration path... but still, it wouldn't really benefit me. I'm not a dub user anyway.)

**Comment by adamdruppe** [comment]
Closing this because the sub subpackage support has improved a lot and now actually shows it all!
