### ISSUE TITLE
difficulties with http2.d

### ISSUE THREAD

**Issue by John-Colvin** [adamdruppe/arsd#89]
Context: trying to download huge number of small files from the same server. Have to reuse the connection otherwise it's _way_ too slow.

What's the best way of achieving this with http2.d? Currently I'm creating a single `HttpRequest` and then setting the `requestParameters.uri` and calling `perform` for each file, but it doesn't seem to work: the `requestParameters.uri` in the response is always the same as the first file...

I'm not that http-savvy so I might just be doing something stupid...

**Comment by adamdruppe** [comment]
On Mon, Jul 11, 2016 at 08:46:39AM -0700, John Colvin wrote:
> What's the best way of achieving this with http2.d? Currently I'm creating a single `HttpRequest` and then setting the `requestParameters.uri` and calling `perform` for each file, but it doesn't seem to work: the `requestParameters.uri` in the response is always the same as the first file...

It should reuse the connection if you share a client.

auto client = new HttpClient();
auto request = client.navigateTo(Uri("url here"));
auto response = request.waitForCompletion();


And then navigate to different places and it should reuse.

http2 is still undergoing a lot of flux, I'm not quite happy with it yet, but if you are doing a bunch of gets you should be ok.

Or async, instead of waitForCompletion, do request.send() for a bunch of them then waitForCompletion after sending them all. But if they are all the same server I'm not sure how much that will help. IIRC it will open at least two simultaneous connections though.

**Comment by John-Colvin** [comment]
Ah, I see. I had missed the `static` around the stuff at the start of HttpRequest and thought that making a new HttpRequest would mean I wasn’t sharing connections.

**Comment by adamdruppe** [comment]
How well is the module working for you by the way?

**Comment by John-Colvin** [comment]
It was working ok, I think... Then I accidentally deleted my code instead of the output of said code, so I gave up and did something different! I'll let you know how it goes if I try using it again :)
